#!/bin/bash
echo "Hello, Welcome :)"
weather_data=$(curl "--silent --output /dev/null https://api.weatherapi.com/v1/current.json?key=4c56e493647d48b7982114636250507&q=TW13%204AG&aqi=no")
location=$(echo $weather_data | jq ".location.name")
echo "Your current location is : " $location
temperature=$(echo $weather_data | jq ".current.heatindex_c")
echo "Temperature : " $temperature
feels_temp=$(echo $weather_data | jq ".current.feelslike_c")
echo "Feels like : " $feels_temp
condition=$(echo $weather_data | jq ".current.condition.text")
echo "Condition Outside : " $condition
